### ISSUE TITLE
Health problems

### ISSUE THREAD

**Issue by 498525451** [games647/ChangeSkin#108]
I'm now using the latest version of firefox 3.0.
Every time you change your skin, you report a mistake.It is the player's health that is greater than 20.
I hope you can solve this problem.
The configuration file is generated by the plug-in without any changes.
The list of plug-ins is only the ESS Vault SkillAPI+ attachment.
Error:
[22:42:18] [Server thread/INFO]: 奥巴驴 issued server command: /skin set tuzi
[22:42:18] [Server thread/WARN]: [ChangeSkin] Task #19114 for ChangeSkin v3.0 generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 119.0. (attribute base value: 20.0, player: 奥巴驴)
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:102) ~[patched_1.11.2.jar:git-Paper-1104]
	at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.setMaxHealth(SkinUpdater.java:248) ~[?:?]
	at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:137) ~[?:?]
	at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
	at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
	at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]****
I'm from China, and your "ChangeSkin", I like it very much, it feels great.The server USES some RPG plug-ins, so the amount of blood is more than 20, and the request fixes this "feature"The server version 1.11.2PS, of course, is the latest version.

**Comment by games647** [comment]
Please follow the issue template

**Comment by 498525451** [comment]
I'm sorry I'm here for the first time. Maybe I made a mistake.

**Comment by games647** [comment]
Just post all everything to actual fix it. See this: https://raw.githubusercontent.com/games647/ChangeSkin/master/.github/ISSUE_TEMPLATE.md

**Comment by Feerko** [comment]
i have the same problem, i have an item that increase player's max health and when i type '/setskin Feerko' many times my health always increase.

**Comment by games647** [comment]
As always the question about your build version (sorry, but just to make sure) and how do you give yourself this item for testing.

**Comment by Feerko** [comment]
I'm always using the newest version from github ;p

**Comment by games647** [comment]
@Feerko Minecraft 1.11 too?

**Comment by Feerko** [comment]
1.12.2
