### ISSUE TITLE
Plugin dont work/MySql don't respond BUNGEECORD

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#111]
### What behaviour is observed:
After using command /skin NICK skin doesnt change.

### What behaviour is expected:
Skin change to another and save new skin

### Steps/models to reproduce:
It happens only when im using bungeecord. When i checked it on spigot server - it work even with MySQL server. 

### Plugin list:
ProtocolLib, ChangeSkin (on BC)

### Environment description
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ca8f31b:1298
MySQL

### Plugin version or build number (don't write latest):
3.0 buld #54

### Error Log:
No error log in console

### Configuration:
default-skins: []
restoreSkins: true
instantSkinChange: true
skinPermission: true
cooldown: 0
mojang-request-limit: 600
server-blacklist: []
upload-accounts: []
auto-skin-update: -1
storage:
    driver: com.mysql.jdbc.Driver
    host: xxx.xxx.xxx.xxx
    port: 3306
    database: skin2
    username: xxx
    password: xxx
proxies:

**Comment by games647** [comment]
Do you followed the Bungee setup guide?

**Comment by andramil** [comment]
I have plugin on both servers - spigot and bungee
I have turn on bungee on spigot config
I have set MySQL database

When new player enters game he gets his skin.
When I use /skin command on spigot server connected to this same database and I have set new skin, this new skin is set on bungecord server too. So there is some connection between server/plugin and database. It dont work when I use /skin command on BC server.

**Comment by games647** [comment]
Could you post the plugin log anyway.

**Comment by games647** [comment]
Could you post the log from the spigot server?

**Comment by andramil** [comment]
In spigot logs there was absolutly nothing

After updating to #55 it started to working (both default skins and connecting to MySQL)

After update:

`[14:13:24 INFO]: UUID of player Cry_Sis is a37f7290-15fb-316f-9d4b-79c9e6e6eef4
[14:13:24 INFO]: Cry_Sis[/46.169.56.196:37233] logged in with entity id 605 at ([world]32.43233878243956, 71.0, 247.56039050433492)
[14:13:30 INFO]: [ChangeSkin] Instant update for Cry_Sis
[14:13:30 WARN]: [ChangeSkin] Task #175 for ChangeSkin v3.0 generated an exception
java.lang.NoSuchFieldError: COMBAT_UPDATE
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.setItemInHand(SkinUpdater.java:238) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:138) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[14:13:48 INFO]: UUID of player janek123 is e353a2d2-8116-36c4-af0c-b2b214e9cae5
[14:13:48 INFO]: janek123[/46.169.56.196:59034] logged in with entity id 623 at ([world]35.736839797784555, 71.0, 244.86675398504448)
[14:14:06 INFO]: [ChangeSkin] Instant update for janek123
[14:14:06 WARN]: [ChangeSkin] Task #191 for ChangeSkin v3.0 generated an exception
java.lang.NoSuchFieldError: COMBAT_UPDATE
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.setItemInHand(SkinUpdater.java:238) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:138) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server2.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[14:14:14 INFO]: janek123 lost connection: Disconnected
[14:14:14 INFO]: janek123 left the game.
[14:14:16 INFO]: UUID of player janek123 is e353a2d2-8116-36c4-af0c-b2b214e9cae5
[14:14:16 INFO]: janek123[/46.169.56.196:48643] logged in with entity id 749 at ([world]35.13598827493569, 71.0, 245.4707375698254)
[14:14:53 INFO]: UUID of player testowegracz is 7bbcd94b-31cf-3540-9656-a831f78ee874
[14:14:53 INFO]: testowegracz[/46.169.56.196:45343] logged in with entity id 831 at ([world]42.5, 72.0, 230.5)
[14:14:53 INFO]: Creating empty config: /root/testowy/plugins/Essentials/userdata/7bbcd94b-31cf-3540-9656-a831f78ee874.yml
`

**Comment by games647** [comment]
Outdated ProtocolLib.

**Comment by andramil** [comment]
there is 4.3.0 protocl lib

**Comment by andramil** [comment]
Ok updated to #390 protocollib bdev build. No exeptions in log

**Comment by andramil** [comment]
Last question - if I have BC  I must have plugin on both spigot and BC server, but have I to change config in spigot server or just Bungee?

**Comment by games647** [comment]
Just BungeeCord, only the messages should be changed on all locations. But you could just symlink the configs if there are on one server.
