### ISSUE TITLE
Default skin crashes plugin

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#112]
### What behaviour is observed:
Default skin doesnt work. ChangeSkin dont load - mark as RED in plugin list

### What behaviour is expected:
Nonpremium people without set skin gets default one

### Steps/models to reproduce:
Plugin can't start with default skin in config. 

### Plugin list:
ChangeSkin, ProtocolLib - (Bungeecord)
Essentials, Vault, ProtocolLib, ChangeSkin, WorldEdit, WorldGuard, (Spiggot)

### Environment description
BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ca8f31b:1298
MySQL
spigot 1.8.8

### Plugin version or build number (don't write latest):
3.0 buld #54

### Error Log:
```
[ChangeSkin] Error loading config. Disabling plugin...
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 12, column 1:
    default-skins: []
    ^
expected <block end>, but found BlockSequenceStart
 in 'reader', line 13, column 5:
        - 73808511-bb53-442f-9e26-25af71 ... 
        ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:410) ~[server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:91) ~[ChangeSkin.jar:?]
	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:77) ~[ChangeSkin.jar:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.loadFile(ChangeSkinCore.java:167) ~[ChangeSkin.jar:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:62) ~[ChangeSkin.jar:?]
	at com.github.games647.changeskin.bukkit.ChangeSkinBukkit.onEnable(ChangeSkinBukkit.java:51) [ChangeSkin.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server2.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

### Configuration:
default-skins:
    - 73808511-bb53-442f-9e26-25af71093582
restoreSkins: true
instantSkinChange: true
skinPermission: true
cooldown: 0
mojang-request-limit: 600
server-blacklist: []
upload-accounts: []
auto-skin-update: -1
storage:
driver: com.mysql.jdbc.Driver
host: xxx.xxx.xxx.xxx
port: 3306
database: skin2
username: xxx
password: xxx
proxies:

**Comment by games647** [comment]
You have to quote the UUID

**Comment by andramil** [comment]
After changing into:

`# If this list is empty no skin will be selected
default-skins:
    - "73808511-bb53-442f-9e26-25af71093582"

# If the player does not have a skin and hasn't chosen one with /setskin`

I have this error in console:

`11:30:30 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
11:30:30 [SEVERE] [ChangeSkin] Error loading config. Disabling plugin...
java.lang.NullPointerException
    at com.github.games647.changeskin.core.ChangeSkinCore.loadDefaultSkins(ChangeSkinCore.java:191)
    at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:76)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:77)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:30:30 [INFO] Enabled plugin ChangeSkin version 3.0 by games647, https://github.com/games647/ChangeSkin/graphs/contributors
`

Plugin still don't load. (checked, after command /skin I have communicat "Command not found")
