### ISSUE TITLE
Bungeecord error

### ISSUE THREAD

**Issue by McJoker123** [games647/ChangeSkin#129]
[SEVERE] ??? 22, 2018 6:32:03 PM changeskin.hikari.HikariConfig setDriverClassName
SEVERE: Failed to load driver class org.sqlite.JDBC from HikariConfig class classloader net.md_5.bungee.api.plugin.PluginClassloader@9f71a9

18:32:03 [SEVERE] [ChangeSkin] Error loading config. Disabling plugin...
java.lang.RuntimeException: Failed to load driver class org.sqlite.JDBC in either of HikariConfig class loader or Thread context classloader
    at changeskin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:529)
    at com.github.games647.changeskin.core.SkinStorage.<init>(SkinStorage.java:41)
    at com.github.games647.changeskin.core.ChangeSkinCore.setupDatabase(ChangeSkinCore.java:112)
    at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:79)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:77)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

can not install on bungeecord help please

**Comment by games647** [comment]
Please follow the BungeeCord setup guideline. There you can see that the last steps tells you to configure MySQL/MariaDB, because BungeeCord has no driver for SQLite (Spigot does).
