### ISSUE TITLE
ChangeSkin cannot encode old slim models

### ISSUE THREAD

**Issue by Feerko** [games647/ChangeSkin#133]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Alex skin doesn't work

### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Bungeecord / mysql

### Plugin version or build number:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
3.1-SNAPSHOT-de520f3

Ok, so i'm trying to connect your plugin with mineskin. It's works always for steve models and only sometimes for alex idk why.

```json
{"timestamp":1504629230114,"profileId":"d1cec9ad1da84179b1e5604f72bfb226","profileName":"rutger465","signatureRequired":true,"textures":{"SKIN":{"metadata":{"model":"slim"},"url":"http://textures.minecraft.net/texture/519b73379fc41cb16b985f371d1917bf6e4dc99809640dd6ad5386b99a664c"}}}
```

https://api.mineskin.org/get/id/43035

```PHP
  $stmt = $conn->prepare("INSERT INTO skinData (SkinID, DisplayName, Timestamp, UUID, Name, SlimModel, SkinURL, CapeURL, Signature) VALUES (NULL, NULL, ?, ?, ?, ?, ?, ?, ?);");
  $stmt->bind_param("sssssss", $Timestamp, $UUID, $Name, $SlimModel, $skinURL, $CapeURL, $Signature);

  $mineskin_json = file_get_contents('http://api.mineskin.org/get/id/' . htmlspecialchars($_GET['mineskin']));
  $mineskin = json_decode($mineskin_json, true);

  $Value = $mineskin["data"]["texture"]["value"];
  $json = base64_decode($Value);
  $array = json_decode($json, true);

  $Timestamp = $array["timestamp"];
  $UUID = $array["profileId"];
  $Name = $array["profileName"];

  if (isset($array["textures"]["SKIN"]["metadata"]["model"])) { $SlimModel = true; }
  else { $SlimModel = false; }

  $skinURL = str_replace('http://textures.minecraft.net/texture/', '', $array["textures"]["SKIN"]["url"]);
  $CapeURL = '';
  $Signature = base64_decode($mineskin["data"]["texture"]["signature"]);

  $stmt->execute();
```
that's my code.

**Comment by Feerko** [comment]
I'm create the same skin using steve model and it works.

https://mineskin.org/167637

```vbs
{"timestamp":1522881394441,"profileId":"da7465ed29cb4de0934d920174491355","profileName":"DancingDoggo_","signatureRequired":true,"textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/519b73379fc41cb16b985f371d1917bf6e4dc99809640dd6ad5386b99a664c"}}}
```

**Comment by Feerko** [comment]
I test the same skin using SkinsRestorer on other server and this skins works, but SkinsRestorer just uses signature as string in database.

**Comment by games647** [comment]
Please always post the encoded data too, because the data isn't the same now. I get a different timestamp now.

>$stmt = $conn->prepare("INSERT INTO skinData (SkinID, DisplayName, Timestamp, UUID, Name, SlimModel, SkinURL, CapeURL, Signature) VALUES (NULL, NULL, ?, ?, ?, ?, ?, ?, ?);");

BTW You could discard SkinID and DisplayName. They will be automatically assigned with their default values.

Could you verify if the encoded signature is still the same after fetching it from MySQL? Do you check if the slim model was correctly detected from your code and inserted into the table?

**Comment by Feerko** [comment]
for skin 43029 in database i get:
Timestamp: 1504629230114
UUID: d1cec9ad1da84179b1e5604f72bfb226
Name: rutger465
SlimModel: 1
SkinURL: 519b73379fc41cb16b985f371d1917bf6e4dc99809640dd6ad5386b99a664c
CapeURL: 
Signature: 
[skinData-Signature.bin.zip](https://github.com/games647/ChangeSkin/files/1879151/skinData-Signature.bin.zip)

**Comment by Feerko** [comment]
Idk how to compare this file to encoded signature from php. You can check what i'm get here: http://api.feerko.pl/beta/newskin.php

**Comment by games647** [comment]
>Idk how to compare this file to encoded signature from php. You can check what i'm get here: 

So this is the data from the MySQL server or from extracting it from MineSkin?

**Comment by Feerko** [comment]
(String) Signature from https://api.mineskin.org/get/id/43035:
```vbs
FqiJXjKiEp3J9tK/VL/AwmB9ZHSvbOy9J9If1SYkiJM1WvhINm3kAeLOCeL/Tr8FvwuP0uHiLbn5P0b5qglIjxIt9RIZeJT/PazsXHuVQO0yTub1+mftu4EwtTxKj0fX1PV7vsXhlL43nZ/ucQFyRISYctbvHTaUayGmiLutPkHnSqKOv3iM06svzS4UvjOnP8/llflVgt7cYjln1Tn0Y2sSwHpVedcLcBroDIXBM1z369gavI6i9VG+BbLPm+wj7+bi78jbBxrUmxvsvD9uBEdwZub6W1ZGGk4ev0D7jucoC494PNOSpojOdOKgH1ctHwxkjONiTmBmq0g5I1I6JQSS5F9+K/kPtMh0vtT3ff9AZxjAQ+dNyYrIQWh4ma19pNVyKQNtXjacowoXmAPeKzajklc6/u8ZFAwiJzPZsIKhVrUZBUXPQ/mJzlbryORqid05rjWOnhHqIDGtyEz2+aof84uk20EnENDznmtq+GsuzEo6IPDf/H20Y/+9WIOzgY32LK0s6wGQschgyNHiFIyMbmzLnHwgoOXm67s6fKWa9ovgTzcXndsO5hDjjL3En2NfPADkXZP1u201FW8Px6qZUhSXOxmJSqPDYSlEaiZw5yx2Vtq/ylSoZsG8iFWezIg9cxF4Z1lLkPeQMioFX9EvL0anlitc/TUFtOFoiHA=
```

Signature from php's base64_decode:
http://api.feerko.pl/beta/newskin.php

Signature from mysql db:
[skinData-Signature.bin.zip](https://github.com/games647/ChangeSkin/files/1879219/skinData-Signature.bin.zip)

**Comment by Feerko** [comment]
```vbs
  $stmt = $conn->prepare("INSERT INTO skinData (Timestamp, UUID, Name, SlimModel, SkinURL, CapeURL, Signature) VALUES (?, ?, ?, ?, ?, ?, FROM_BASE64(?));");
  $stmt->bind_param("ississs", $Timestamp, $UUID, $Name, $SlimModel, $skinURL, $CapeURL, $Signature);

  $mineskin_json = file_get_contents('http://api.mineskin.org/get/id/' . htmlspecialchars($_GET['mineskin']));
  $mineskin = json_decode($mineskin_json, true);

  $Value = $mineskin["data"]["texture"]["value"];
  $json = base64_decode($Value);
  $array = json_decode($json, true);

  $Timestamp = $array["timestamp"];
  $UUID = $array["profileId"];
  $Name = $array["profileName"];

  if (isset($array["textures"]["SKIN"]["metadata"]["model"])) { $SlimModel = true; }
  else { $SlimModel = false; }

  $skinURL = str_replace('http://textures.minecraft.net/texture/', '', $array["textures"]["SKIN"]["url"]);
  $CapeURL = '';
  $Signature = $mineskin["data"]["texture"]["signature"];
```

This is my code for now. There is no php error but still doesn't work. I'm still alex.

**Comment by Feerko** [comment]
That's werid. I have script that set my slot 4 to player's skull and I'm getting head from new skin but i'm still alex.

<img width="146" alt="zrzut ekranu 2018-04-05 o 11 36 57" src="https://user-images.githubusercontent.com/16988054/38358537-cce7bdf0-38c5-11e8-8347-cad0ed11ec55.png">

**Comment by games647** [comment]
Please post the new row result and try to rejoin in game.

**Comment by Feerko** [comment]
Timestamp: 1504629230114
UUID: d1cec9ad1da84179b1e5604f72bfb226
Name: rutger465
SlimModel: 1
SkinURL: 519b73379fc41cb16b985f371d1917bf6e4dc99809640dd6ad5386b99a664c
[skinData-Signature.bin.zip](https://github.com/games647/ChangeSkin/files/1879455/skinData-Signature.bin.zip)

**Comment by Feerko** [comment]
After relog the same problem.

**Comment by games647** [comment]
The file stills shows a different result. Could you do a var_dump on the signature variable please and verify it with 

```SQL
SELECT `SkinURL`,TO_BASE64(`signature`) FROM `skinData`;
```

**Comment by Feerko** [comment]
```vbs
{ "SkinURL": "519b73379fc41cb16b985f371d1917bf6e4dc99809640dd6ad5386b99a664c", "TO_BASE64(`signature`)": "FuNKRcvEN8xSC8AD3NLjUBosZzyDWO1KKKU9mxw\/plGOmj3zXGkgi4l7J1jGmXRmXSnpQtHl0bPn\n1u68VTbE4q8sdfc3tn8q5J\/X\/oDs7cO1kSC\/R3Qb5KjMIzbbUknwumhgyWv8YkRlrLNpYDOKcX\/0\nnJq1Cdc15CchAd\/vWlW3vn\/Cnlfgw9FAslE2qmYkX3TaXsjthaPaTwKPyYfzQf7yFckCO50mMgcY\nhzCXsIo6OPSPxRNdbAbtIjs\/qua89G5FTRO8mep\/sGNmG8+UseTjM6iAZfJkVx0+ubJ4qwFifHhT\nnEAYBqM6vybUK9mJmUqFQqgItGUqva\/U1wNRQU1Gh74jvL8Yi1fEu2OnhZLpxAeR8mA9nkTeVnAV\nsO2ww7mm6SmFAwuxF5v08mll0EGg+h4CKC+PsecfMW1aw5jJcpDmmhdOzF1MFYy5N4iYWYEiJR4K\nlBjtGsBwXtSefcpqKXDHovXb1DFM+VlA4f181D2jRvjIRrVtfLi2Oeue4H+u4cc1TZiLqlDrHmUO\nWA0pUpZ\/K62KC\/\/JyyvMXCAVfm7xNkBNtVg58BoBb+skDbpQBm\/iViN17wGQWKvSTgWwsa7xjDVY\nwKKonEIREA5kI5QS8EWDxJAtvwnuc5izWwQQZTzpEcrLmbXiqUrIr6gDgGPGZR41L2JeFUpPsEQ=" }
```

**Comment by games647** [comment]
Please var_dump the signature variable from extracting it from MineSkin.

**Comment by Feerko** [comment]
```vbs
MFwzkLyRyUeBYsRPSXA930Ls/3wYDv9Jz0LjX+pjB4IB8Ae7wA45yTe18Nd3Wxl5W7FxHN/OK5T10zEC6WdAb1oF3H9nfhqNevpJWpohI3Ff+hlQoMy05YyfhdMhwuP8z72QSZ5SNsW8Ysds8Uxe48RKVBIiwuUZ+79ekMDxeeI7wgpsl3mViKQmzZcI7pn5x07LARt6NqgFT2mBaO6WWwAYjlDQm2UiKtL0hmkQ5j9eD0K5mHQscdKBKcNdts3mnE8cXBcfK5NDqowKfxT7QsDq0kEvCPuES2RDunxaB2aIIG2NEpKk3fTMhGhrdbfRvuKzi72nVr0QD7FGhxQ5ehuZ+stUcbZN+SuRqj1Iz18Av8/XvGawoQxm+f+J1PasZxSDMdnmQgE0P0phAKKnSDTRlJT/QY1hvKKB3mnsbj9z6NXw4Po7XKwo1IE4IwWVltu8cUMGZ1kpET7IbpNcastDhFtNWhJTQDFnw29EcCFmIYSVyeEn66kprOTM2ACx2a2Uq3qTqtbqVspkiqcdq2Kx5SYZvy0p4rWALq6HxcslBecQKTm36A59Nn+yWom3fUZP+YULqZ7NzR9VU8E4BEx0WZ3YNVSKMoq99LATFQrESuoKOlIZSSA+Ns/RnOb+dXWKHPGbmgM2MQ5UH6F2XJZxtQ2s1mXu4ByisBhc0fY=
```

**Comment by Feerko** [comment]
and with base64_decode http://api.feerko.pl/beta/test.php

**Comment by games647** [comment]
That seems to be the signature of a different thing, because it doesn't match your result row you posted, but the signature seems to be correct now. Do you deleted the invalid values from the table? That could be the reason that the skin doesn't work in game.

**Comment by Feerko** [comment]
I will try to generate new skin and I'll upload everything

**Comment by Feerko** [comment]
Oh i see... I just set id from changeskin instead of id mineskin in mineskin api.

http://api.feerko.pl/beta/test.php

**Comment by games647** [comment]
Do you tried to delete the invalid rows, restart the server and rejoin?

**Comment by Feerko** [comment]
Yes and there is still alex.

**Comment by games647** [comment]
Please verify that you have a correct skin with /skin-info

**Comment by Feerko** [comment]
hmm...
<img width="681" alt="zrzut ekranu 2018-04-05 o 14 29 59" src="https://user-images.githubusercontent.com/16988054/38365785-ebfe377e-38dd-11e8-88b1-a86c08cc51a0.png">

```vbs
[12:31:47] [Netty Worker IO Thread #5/WARN]: Error in dispatching command
java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to net.md_5.bungee.api.connection.PendingConnection
	at com.github.games647.changeskin.bungee.command.InfoCommand.execute(InfoCommand.java:35) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:168) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:115) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at de.rayzon.Command4Me.event.PluginMessage.onListenChannel(PluginMessage.java:36) [Command4Me.jar:?]
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:411) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:246) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:75) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by games647** [comment]
Fixed

**Comment by Feerko** [comment]
```vbs
[14:45:19] [Netty Worker IO Thread #6/WARN]: Error in dispatching command
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_151]
	at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_151]
	at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_151]
	at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_151]
	at net.md_5.bungee.api.chat.TextComponent.fromLegacyText(TextComponent.java:50) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.api.chat.TextComponent.fromLegacyText(TextComponent.java:32) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at com.github.games647.changeskin.bungee.command.InfoCommand.execute(InfoCommand.java:38) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:168) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:115) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:145) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:ab638e2:173]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

still error

**Comment by games647** [comment]
That's great BungeeCord configuration doesn't return all keys when used with .getKeys(). It should be fixed now.

**Comment by Feerko** [comment]
fow now all skins doesn't work, i can't select skin by id. I'm get 'Skin not found'

**Comment by games647** [comment]
How do you invoked the command?

**Comment by Feerko** [comment]
/skin-select 106992
/skin-select skin-106992
and doesn't work

but /setskin notch works

**Comment by games647** [comment]
Do you check if that's the correct row number in your database?

**Comment by Feerko** [comment]
<img width="914" alt="zrzut ekranu 2018-04-05 o 18 36 23" src="https://user-images.githubusercontent.com/16988054/38379201-455d305a-3900-11e8-871e-b36a6eb11c49.png">

yes

**Comment by games647** [comment]
The plugin will also return this message if there is SQL error.

**Comment by Feerko** [comment]
ChangeSkin.db was created in my folder after update. I don't change my config,

**Comment by Feerko** [comment]
Still doesn't work... ChangeSkin.db creating in plugin's folder

**Comment by Feerko** [comment]
Ok, last commit fix command but this skin https://api.mineskin.org/get/id/43035 still doesn't work.

**Comment by games647** [comment]
As I said please run /skin-info

**Comment by Feerko** [comment]
<img width="724" alt="zrzut ekranu 2018-04-05 o 19 52 24" src="https://user-images.githubusercontent.com/16988054/38382731-ff708b18-390a-11e8-974a-d7a3f503ee60.png">

**Comment by games647** [comment]
>In my code is everything fine, skins what doesn't work in changeskin works normal in skinrestorer so idk

You can't compare those two things, because SkinsRestorer doesn't decode the skins at all. Please post the complete row as file.

**Comment by games647** [comment]
Okay I found the source. If you closely, you can see that the order of metadata and url is different. For some reason Mojang changed this format and now we have a mixed format.

**Comment by Feerko** [comment]
there is way to fix this in plugin side?

**Comment by Feerko** [comment]
i have a lot of data in database where doesn't works slim skins

**Comment by games647** [comment]
Could you give some names, maybe we could find a pattern. It looks like it was a certain time when they changed it. Every newer skin requests from Mojang has the order url and then metadata like ChangeSkin detects. Older ones have metadata and then URL.

**Comment by Feerko** [comment]
There is way to fix this?

**Comment by games647** [comment]
Yes I'm working on it. Currently it's possible with newer skins than X or check if the signature is valid and if not try the other way.

**Comment by games647** [comment]
It should be fixed now. Besides that as you can see, I cleaned up this ticket a bit in case someone else searches for the same bug.

Sorry for not finding this bug earlier, I properly wasted an entire day for you.

**Comment by Feerko** [comment]
Works great for now, thanks a lot! :)
