### ISSUE TITLE
NoSuchMethodError: com.nametagedit.plugin.api.INametagApi.reloadNametag(Lorg/bukkit/entity/Player;)V

### ISSUE THREAD

**Issue by mckite** [games647/ChangeSkin#140]
### What behaviour is observed:
[//]: # (What happened?)
Using skin command, the skin set  OK but, spam the error in console

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

### Plugin list:
[//]: # (This can be found by running `/pl`)

Authme, ProtocoSupport , ChangeSkin, AAC , NameTagEdit, ProtocolLib, Essentials , Worldedit , WorldGuard, PermissionsEX , Skript
### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)

spigot 1.8.8 (Standalone )

### Plugin version or build number:

version 3.0
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)

### Error Log:

[04:52:20 WARN]: [ChangeSkin] Task #496 for ChangeSkin v3.0 generated an exception
java.lang.NoSuchMethodError: com.nametagedit.plugin.api.INametagApi.reloadNametag(Lorg/bukkit/entity/Player;)V
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:144) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
        at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-21fe70
7-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbu
kkit.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe70
7-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
[04:52:28 INFO]: KitePro issued server command: /skin KitePro
[04:52:28 WARN]: [ChangeSkin] Task #534 for ChangeSkin v3.0 generated an exception
java.lang.NoSuchMethodError: com.nametagedit.plugin.api.INametagApi.reloadNametag(Lorg/bukkit/entity/Player;)V
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdateSelf(SkinUpdater.java:144) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.sendUpdate(SkinUpdater.java:102) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.onInstantUpdate(SkinUpdater.java:94) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUpdater.run(SkinUpdater.java:80) ~[?:?]
        at com.massivecraft.massivelag.inject.MassiveLagRunnable.run(MassiveLagRunnable.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-21fe70
7-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [craftbu
kkit.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-21fe707-
e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-21fe70
7-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]

**Comment by games647** [comment]
Please update your NameTagEdit plugin to a dev-build.
