### ISSUE TITLE
No implementation for org.spongepowered.api.network.ChannelBinding$RawDataChannel was bound

### ISSUE THREAD

**Issue by WoOzGaME** [games647/ChangeSkin#142]
I can't run ChangeSkin with my Sponge serveur (1.11)
Here the error:

>[17:11:15] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:11:15] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:11:15] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[17:11:19] [main/INFO] [FML]: Forge Mod Loader version 13.19.1.2195 for Minecraft 1.11 loading
[17:11:19] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_171, running on Windows 10:x86:10.0, installed at C:\Program Files (x86)\Java\jre1.8.0_171
[17:11:19] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.11-2195-6.0.0-BETA-2004.jar
[17:11:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:11:19] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:11:19] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.6.1 Source=file:/C:/Users/Rémi%20BANKA/Desktop/Serveur%201.11/mods/spongeforge-1.11-2195-6.0.0-BETA-2004.jar Env=SERVER
[17:11:19] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[17:11:19] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[17:11:19] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[17:11:19] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[17:11:19] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:11:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:11:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:11:19] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:11:21] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:11:21] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:11:21] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[17:11:24] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@c01636
[17:11:24] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:11:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:11:25] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[17:11:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:11:25] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[17:11:30] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[17:11:32] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:tileentity.MixinTileEntityHopper, previously written by org.spongepowered.common.mixin.core.item.inventory.TraitInventoryAdapter. Skipping method.
[17:11:32] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:tileentity.MixinTileEntityChest, previously written by org.spongepowered.common.mixin.core.item.inventory.TraitInventoryAdapter. Skipping method.
[17:11:32] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:tileentity.MixinTileEntityFurnace, previously written by org.spongepowered.common.mixin.core.item.inventory.TraitInventoryAdapter. Skipping method.
[17:11:34] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:item.inventory.TraitInventoryAdapter, previously written by org.spongepowered.common.mixin.core.entity.passive.MixinEntityVillager. Skipping method.
[17:11:35] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:item.inventory.TraitInventoryAdapter, previously written by org.spongepowered.common.mixin.core.item.inventory.MixinContainer. Skipping method.
[17:11:37] [main/WARN] [mixin]: Method overwrite conflict for getSlotProvider in mixins.common.core.json:item.inventory.TraitInventoryAdapter, previously written by org.spongepowered.common.mixin.core.entity.player.MixinInventoryPlayer. Skipping method.
[17:11:37] [Server thread/INFO]: Starting minecraft server version 1.11
[17:11:37] [Server thread/INFO] [FML]: MinecraftForge v13.19.1.2195 Initialized
[17:11:37] [Server thread/INFO] [FML]: Replaced 231 ore recipes
[17:11:38] [Server thread/INFO] [Sponge]: Found mcmod.info at jar:file:/C:/Users/Rémi%20BANKA/Desktop/Serveur%201.11/mods/spongeforge-1.11-2195-6.0.0-BETA-2004.jar!/mcmod.info
[17:11:40] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.block.tileentity.TileEntityTypes.ENCHANTMENT_TABLE
[17:11:40] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.block.tileentity.TileEntityTypes.NOTE
[17:11:40] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.block.tileentity.TileEntityTypes.STRUCTURE
[17:11:40] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.type.HorseVariants.LLAMA
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.ACHIEVEMENTS
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.AGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.ATTACK_DAMAGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.BASE_SIZE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.DAMAGE_ENTITY_MAP
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.DOMINANT_HAND
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.END_GATEWAY_AGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.END_GATEWAY_TELEPORT_COOLDOWN
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.EXACT_TELEPORT
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.EXIT_POSITION
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.FILLED
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.FLUID_LEVEL
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.HEALTH_SCALE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.HEIGHT
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.HELD_EXPERIENCE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.IS_SLEEPING
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.JOHNNY_VINDICATOR
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_ATTACKER
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LAST_DAMAGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LEASH_HOLDER
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LLAMA_STRENGTH
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.LLAMA_VARIANT
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.PASSENGERS
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SCALE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_ENTITIES
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_MAXIMUM_DELAY
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_MAXIMUM_NEARBY_ENTITIES
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_NEXT_ENTITY_TO_SPAWN
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_REQUIRED_PLAYER_RANGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_SPAWN_COUNT
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.SPAWNER_SPAWN_RANGE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STATISTICS
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_AUTHOR
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_IGNORE_ENTITIES
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_INTEGRITY
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_MODE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_POSITION
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_POWERED
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_SEED
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_SHOW_AIR
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_SHOW_BOUNDING_BOX
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.STRUCTURE_SIZE
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WILL_SHATTER
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENTS
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_EAST
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_NORTH
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_SOUTH
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.data.key.Keys.WIRE_ATTACHMENT_WEST
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_COLUMN
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_BUTTON
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_ICON
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_CHECKBOX
[17:11:41] [Server thread/WARN] [Sponge]: Skipping org.spongepowered.api.item.inventory.InventoryArchetypes.MENU_SPINNER
[17:11:42] [Server thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:11:42] [Server thread/INFO] [FML]: Searching C:\Users\Rémi BANKA\Desktop\Serveur 1.11\mods for mods
[17:11:42] [Server thread/INFO] [FML]: Searching C:\Users\Rémi BANKA\Desktop\Serveur 1.11\.\mods\plugins for plugins
[17:11:43] [Server thread/INFO] [FML]: Forge Mod Loader has identified 7 mods to load
[17:11:43] [Server thread/WARN] [Sponge]: The mod changeskin was designed for spongeapi 7.0.0. It may not work properly.
[17:11:43] [Server thread/INFO] [FML]: FML has found a non-mod file ProtocolLib.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[17:11:44] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, changeskin] at CLIENT
[17:11:44] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, changeskin] at SERVER
[17:11:45] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[17:11:45] [Server thread/INFO] [FML]: Found 443 ObjectHolder annotations
[17:11:45] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:11:45] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:11:45] [Server thread/INFO] [FML]: Applying holder lookups
[17:11:45] [Server thread/INFO] [FML]: Holder lookups applied
[17:11:45] [Server thread/INFO] [FML]: Applying holder lookups
[17:11:45] [Server thread/INFO] [FML]: Holder lookups applied
[17:11:45] [Server thread/INFO] [FML]: Applying holder lookups
[17:11:45] [Server thread/INFO] [FML]: Holder lookups applied
[17:11:45] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:11:45] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:11:45] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: OUTDATED Target: 13.19.1.2199
[17:11:46] [Server thread/ERROR] [changeskin]: Please choose for Spigot (SQLite, MySQL), Sponge (SQLite, MariaDB) or BungeeCord (MySQL)
[17:11:46] [Server thread/ERROR] [changeskin]: This driver  is not supported on this platform
java.lang.ClassNotFoundException:
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_171]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_171]
        at com.github.games647.changeskin.core.ChangeSkinCore.checkDriver(ChangeSkinCore.java:125) [ChangeSkinCore.class:?]
        at com.github.games647.changeskin.core.ChangeSkinCore.setupDatabase(ChangeSkinCore.java:100) [ChangeSkinCore.class:?]
        at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:73) [ChangeSkinCore.class:?]
        at com.github.games647.changeskin.sponge.ChangeSkinSponge.onPreInit(ChangeSkinSponge.java:56) [ChangeSkinSponge.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_ChangeSkinSponge_onPreInit1.handle(Unknown Source) [?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:201) [SpongeMod.class:1.11-2195-6.0.0-BETA-2004]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:616) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[17:11:46] [Server thread/INFO] [FML]: Applying holder lookups
[17:11:46] [Server thread/INFO] [FML]: Holder lookups applied
[17:11:46] [Server thread/INFO] [FML]: Injecting itemstacks
[17:11:46] [Server thread/INFO] [FML]: Itemstack injection complete
[17:11:46] [Server thread/INFO]: Loading properties
[17:11:46] [Server thread/INFO]: Default game type: SURVIVAL
[17:11:46] [Server thread/INFO]: Generating keypair
[17:11:46] [Server thread/INFO]: Starting Minecraft server on *:25565
[17:11:46] [Server thread/INFO]: Using default channel type
[17:11:46] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:11:46] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:11:46] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:11:46] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:11:47] [Server thread/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=changeskin, name=ChangeSkin, version=3.1-SNAPSHOT-08011cc, description=Change your Minecraft skin in-game, url=https://dev.bukkit.org/bukkit-plugins/changeskin/, source=C:\Users\Rémi BANKA\Desktop\Serveur 1.11\.\mods\plugins\ChangeSkinSponge.jar}
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.spongepowered.api.network.ChannelBinding$RawDataChannel was bound.
  while locating org.spongepowered.api.network.ChannelBinding$RawDataChannel
    for field at com.github.games647.changeskin.sponge.BungeeListener.pluginChannel(BungeeListener.java:20)
  while locating com.github.games647.changeskin.sponge.BungeeListener

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042) ~[InjectorImpl.class:1.11-2195-6.0.0-BETA-2004]
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001) ~[InjectorImpl.class:1.11-2195-6.0.0-BETA-2004]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[InjectorImpl.class:1.11-2195-6.0.0-BETA-2004]
        at com.github.games647.changeskin.sponge.ChangeSkinSponge.onInit(ChangeSkinSponge.java:80) ~[ChangeSkinSponge.class:?]
        at org.spongepowered.common.event.listener.GameInitializationEventListener_ChangeSkinSponge_onInit3.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2004]
        at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:201) [SpongeMod.class:1.11-2195-6.0.0-BETA-2004]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.11.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.11.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzd000(LoadController.java:53) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:797) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:334) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:215) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

Thanks :)

**Comment by games647** [comment]
For the first error. Please read the log. It tells you how to solve it:

>[17:11:46] [Server thread/ERROR] [changeskin]: Please choose for Spigot (SQLite, MySQL), Sponge (SQLite, MariaDB) or BungeeCord (MySQL)
[17:11:46] [Server thread/ERROR] [changeskin]: This driver is not supported on this platform

For the second I pushed an update that should fix it.
