### ISSUE TITLE
Minecraft 1.13.1 No field with type int PacketPlayOutRespawn

### ISSUE THREAD

**Issue by mirolm** [games647/ChangeSkin#153]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
I issued command /setskin nick and error is generated.

### What behaviour is expected:
Change my skin

### Steps/models to reproduce:
I issued /setskin command and in server log exception is generated.

### Plugin list:
Plugins (9): Vault (v1.6.7-b80), Essentials (v2.15.0.45), EssentialsSpawn (v2.15.0.45), LoginSecurity (v2.0.29-a5f398f), GriefPrevention (v16.9.alpha), EssentialsChat (v2.15.0.45), zPermissions (1.4.2-SNAPSHOT build: 094f006), ProtocolLib (v4.4.0-SNAPSHOT-b415), ChangeSkin (v3.1-SNAPSHOT-a053874)

### Environment description
Spigot git-Spigot-2440e18-9636bb8 (MC: 1.13.1), Debian 9, Latest Oracle Java 1.8.0_181, MariaDB 10.3.9

### Plugin version or build number:
ChangeSkin v3.1-SNAPSHOT-a053874

### Error Log:
As something is not good with hastebin i attach error here. Sorry about that.

```
[19:16:37] [Server thread/INFO]: ieti issued server command: /setskin ieti
[19:16:37] [Server thread/WARN]: [ChangeSkin] Task #382 for ChangeSkin v3.1-SNAPSHOT-a053874 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: No field with type int exists in class PacketPlayOutRespawn.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
        at com.github.games647.changeskin.bukkit.task.SkinApplier.sendPacketsSelf(SkinApplier.java:160) ~[?:?]
        at com.github.games647.changeskin.bukkit.task.SkinApplier.sendUpdateSelf(SkinApplier.java:115) ~[?:?]
        at com.github.games647.changeskin.bukkit.task.SkinApplier.applyInstantUpdate(SkinApplier.java:85) ~[?:?]
        at com.github.games647.changeskin.core.shared.task.SharedApplier.applySkin(SharedApplier.java:27) ~[?:?]
        at com.github.games647.changeskin.bukkit.task.SkinApplier.run(SkinApplier.java:73) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411) [spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.1.jar:git-Spigot-2440e18-9636bb8]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

### Configuration:
Standard configuration using MySQL.

**Comment by mirolm** [comment]
I opened an issue in ProtocolLib - [Here](https://github.com/dmulloy2/ProtocolLib/issues/516). Hope it makes code more clean.

**Comment by games647** [comment]
Thank you for the notification. This looks indeed better.
