### ISSUE TITLE
ERROR SPONGE

### ISSUE THREAD

**Issue by LeChevalierDOr** [games647/ChangeSkin#156]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # I hava a error when I start my Sponge server FORGE 1.12.2 

### What behaviour is expected:
[//]: # ``` I have a error/crach when I start my server
```

### Steps/models to reproduce:
[//]: # Run the plugin in SPONGE FORGE 1.12.2 version 3442

### Plugin list:
[//]: # 
```
	|UEE    | changeskin           | 3.0                         | ChangeSkin.jar                                | None                                     |
	| U     | pjc                  | 0.2.2                       | projectcore-7.1.0-0.2.2.jar                   | None                                     |
	| U     | pjw                  | 0.12.2                      | projectworlds-7.1.0-0.12.2.jar                | None                                     |
	| U     | boop                 | 1.6.0                       | Boop-1.6.0.jar                                | None                                     |
	| U     | luckperms            | 4.2.17                      | LuckPerms-Sponge-4.2.17.jar                   | None                                     |
	| U     | pec                  | 0.2.0                       | ParticleEffectCombinator-0.2.0.jar            | None                                     |
	| U     | voxelsniper          | 8.5.0-SNAPSHOT              | VoxelSniper-8.5.0-SNAPSHOT.jar                | None                                     |
	| U     | happytrails          | 0.1.5                       | HappyTrails-0.1.5.jar                         | None                                     |
	| U     | flexiblelogin        | 0.17.4                      | flexiblelogin-0.17.4.jar                      | None                                     |
	| U     | placeholderapi       | 4.4                         | PlaceholderAPI-4.4.jar                        | None                                     |
	| U     | pjp                  | 0.14.3                      | projectportals-7.1.0-0.14.3.jar               | None                                     |
	| U     | clearmob             | 1.12-2.0.1                  | ClearMob-1.12-2.0.1.jar                       | None                                     |
	| U     | worldedit            | 6.1.9-SNAPSHOT              | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar      | None                                     |
	| U     | customrestartmessage | 1.0                         | CustomRestartMessage.jar                      | None                                     |
	| U     | nucleus              | 1.5.2-S7.0                  | Nucleus-1.5.2-S7.0-MC1.12.2-plugin.jar        | None                                     |
	| U     | ultimatechat         | 1.8.8                       | UltimateChat-1.8.8-b196-Universal.jar         | None                                     |
	| U     | universeguard        | 2.15                        | UniverseGuard-2.15.jar                        | None                                     |
	| U     | holograms            | 3.1.5                       | holograms-3.1.5.jar                           | None                                     |
	| U     | gwm_library          | 1.3.4                       | GWMLibrary 1.3.4.jar                          | None                                     |
	| U     | stackban             | 0.3.0                       | stackban-7.1.0-0.3.0.jar                      | None                                     |
	| U     | gwm_crates           | 3.1.13                      | GWMCrates 3.1.13.jar                          | None                                     |
	| U     | catclearlag          | 0.8.3                       | CatClearLag-0.8.3.jar                         | None                                     |
	| U     | magibridge           | 2.4.6                       | Tenavia-Boot.jar                              | None    									|
```
### Environment description
[//]: # Sponge server

### Plugin version or build number:
[//]: #  changeskin 3.0
[//]: #

### Error Log:
[Pastebin] https://pastebin.com/6N38imT7

### Configuration:
[//]: # JAVA 8

**Comment by LeChevalierDOr** [comment]
Resolved sorry =(

**Comment by games647** [comment]
If you have a number as username for your database, format it like this 'Number'.

**Comment by LeChevalierDOr** [comment]
No I use mySQL of my server web .

**Comment by LeChevalierDOr** [comment]
And I have a new error ;
```
[18:03:29] [Server thread/ERROR] [changeskin]: Failed to query skin data from uuid: b9c560a9-fc1f-44a6-a3eb-7d5b463145eb
java.sql.SQLSyntaxErrorException: (conn:110377) Unknown column 'SkinId' in 'field list'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:158) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245) ~[MariaDbStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:167) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[ProxyPreparedStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.github.games647.changeskin.core.SkinStorage.getSkin(SkinStorage.java:163) [SkinStorage.class:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.loadDefaultSkins(ChangeSkinCore.java:224) [ChangeSkinCore.class:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:77) [ChangeSkinCore.class:?]
	at com.github.games647.changeskin.sponge.ChangeSkinSponge.onPreInit(ChangeSkinSponge.java:65) [ChangeSkinSponge.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_ChangeSkinSponge_onPreInit59.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3442]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.sql.SQLException: Unknown column 'SkinId' in 'field list'
Query is: SELECT SkinId, Timestamp, UUID, Name, SlimModel, SkinUrl, CapeUrl, Signature FROM skinData WHERE UUID=? ORDER BY Timestamp DESC LIMIT 1, parameters ['b9c560a9fc1f44a6a3eb7d5b463145eb']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146) ~[LogQueryTool.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223) ~[AbstractQueryProtocol.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	... 47 more
[18:03:29] [Server thread/ERROR] [changeskin]: Failed to query skin data: SkinModel{rowId=-1, encodedValue='eyJ0aW1lc3RhbXAiOjE1MzcyMDAyMDk1NjEsInByb2ZpbGVJZCI6ImI5YzU2MGE5ZmMxZjQ0YTZhM2ViN2Q1YjQ2MzE0NWViIiwicHJvZmlsZU5hbWUiOiJFbmdhcmltQXh0c2NobGFnIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80MGYzMWQwY2UwZmJmYTAzMzdlMjEyNTQxNThlOThjMTNjYWQ4NDM4ZWE4NGRiNmJlNGNkOWFhMmM1OTM4YmU0In19fQ==', encodedSignature='Y03GXUa0b6/AlWo1/uMROM9SpufwKx12bftFPhW1xzHf986uscWUaAb3XaK9QjIQggQf87yDGj+5Bmql2K4gOg61/8RxC9nLWj5kudw0ydIZjpO5mRFPXdJpKBcTHJ18I37hDdBhuVx6Yvq/vHBTr2DeUwW1Y6KOdXcxmZYHQmV8NqPjgk3xuCN/9+4WBNs9OcV3UKlwTdckqzPOOqF2YR5dnAyfovCeg1fPFhNR9T/EuIrWPiTlAdGWyiv5SARYYHxouaWv1irefn5MPtPSUYUDgbbQga4NbLDZ0VFzrdRDapsqGozlLlvHwJk1bVzZu0gvapOamW5XpcaAp6kUw9fyzfBtt/x3cgV7bobcM/ij9gXrJ9CvP2eHI/AyfKmAD8synMhIg5MgiQSEJf9xXxoR3zElzET+T60VFtM0ahLiLE4P2sWWc7xwT+jIhu4Acu1VxtVl7dsnUjDhQ5va/Gty2FlVvkJLuYz5RMBPa5khFA6MUXb1P8g2h2g6zWwC2Hx7jC+MB6cQuHL0MBeZN2Y5iM9e9QPjUWHErHBD5z0lrouH5XOGYwYBmcU8X7feSONqPUPljWXyI8FJbax4hRF/Bkrk8UdLqwAtviTPrvRT2EAtC9F96+ovyRdDswmIPLpQa4jccrzATCIBV20ZZ3ZZGi6gQdiQJSUSWH9LYjQ=', timestamp=1537200209561, profileId=b9c560a9-fc1f-44a6-a3eb-7d5b463145eb, profileName='EngarimAxtschlag', signatureRequired=true, textures={SKIN=TextureModel{url='http://textures.minecraft.net/texture/40f31d0ce0fbfa0337e21254158e98c13cad8438ea84db6be4cd9aa2c5938be4', metadata=null}}}
java.sql.SQLSyntaxErrorException: (conn:110377) Unknown column 'Timestamp' in 'field list'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:158) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:118) ~[ExceptionMapper.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:245) ~[MariaDbStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:218) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:153) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeUpdate(MariaDbPreparedStatementClient.java:186) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[ProxyPreparedStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariProxyPreparedStatement.class:1.12.2-2705-7.1.0-BETA-3442]
	at com.github.games647.changeskin.core.SkinStorage.save(SkinStorage.java:267) [SkinStorage.class:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.loadDefaultSkins(ChangeSkinCore.java:230) [ChangeSkinCore.class:?]
	at com.github.games647.changeskin.core.ChangeSkinCore.load(ChangeSkinCore.java:77) [ChangeSkinCore.class:?]
	at com.github.games647.changeskin.sponge.ChangeSkinSponge.onPreInit(ChangeSkinSponge.java:65) [ChangeSkinSponge.class:?]
	at org.spongepowered.common.event.listener.GamePreInitializationEventListener_ChangeSkinSponge_onPreInit59.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:271) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3442]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.sql.SQLException: Unknown column 'Timestamp' in 'field list'
Query is: INSERT INTO skinData (Timestamp, UUID, Name, SlimModel, SkinURL, CapeURL, Signature) VALUES (?, ?, ?, ?, ?, ?, ?), parameters [1537200209561,'b9c560a9fc1f44a6a3eb7d5b463145eb','EngarimAxtschlag',0,'40f31d0ce0fbfa0337e21254158e98c13cad8438ea84db6be4cd9aa2c5938be4','',<bytearray:cM�]F�o���j5��8�R���+vm�E>��1��ή�Ŕh�]��B2��?�j�خ :���q��Z>d��4������O]�i(�|#~�
�a�\zb���pS�`�S�c��uw1��Be|6��M�#���=9�wP�pM�$�3�:�va]����W�Q�?ĸ��>$�і�+�HX`|h����*�~~L>��Q���Ё�
l���Qs��Cj�*��.[���5m\ٻH/j���nW�ƀ�������m��wr{n��3����'Я?g�#�2|���2��H�� ��%�q_�1%�D�O��4j�,N�Ŗs�pO�Ȇ�r�U��e��'R0�C���kr�YU�BK���D�Ok�!�Qv�?�6�h:�l�|{�/���r�0�7f9��^��QaĬpC�=%����s�c��<_��H�j=C�e�#�Im�x�J��GK�-�$Ϯ�S�@-�}��/�C�	�<�Pk��r��L"WmgvY.�Aؐ%%XKb4>]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146) ~[LogQueryTool.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.i
```nternal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:223) ~[AbstractQueryProtocol.class:1.12.2-2705-7.1.0-BETA-3442]
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:212) ~[MariaDbPreparedStatementClient.class:1.12.2-2705-7.1.0-BETA-3442]
	... 47 more

**Comment by LeChevalierDOr** [comment]
My username name his tenavia_b... and I don't have a number

**Comment by LeChevalierDOr** [comment]
The server logs ask me : 

> Please choose for Spigot (SQLite, MySQL), Sponge (SQLite, MariaDB) or BungeeCord (MySQL)

But I use SQL it's same to MariaDB? sorry for this question but I know only MySQL and SQLite . . .

Edit: I make personal research and I found that MariaDB is implemented in MySQL is that?

**Comment by LeChevalierDOr** [comment]
The name of the table in BDD is {TABLE_NAME} . . .
I can use my web BDD ?

**Comment by LeChevalierDOr** [comment]
I thing it's SQL error from your plugin :

Unknown column 'SkinId' in 'field list'
Unknown column 'Timestamp' in 'field list'

**Comment by games647** [comment]
You have to let the plugin create the table.

>I reinstall the plugin and In the driver parameters for database I put com.mysql.jdbc.Driver but

Sponge doesn't include that driver. You have to use the MariaDB (fork of MySQL) driver which is backswards compatible to MySQL.

>I can use my web BDD ?

Yes you can, either by expanding the table, using foreign keys or issuing multiple queries.

**Comment by LeChevalierDOr** [comment]
- You have to let the plugin create the table.
I don't understand ...

Yes but if I put **com.mariadb.jdbc.Driver** in the parameters for database i get a error

**Comment by games647** [comment]
>I don't understand ...

You should only provide the database. The plugin will create a table on it's own if it doesn't exist. On first use that table shouldn't exist or should be in the same format of like here:

https://github.com/games647/ChangeSkin/blob/646f6fa6b8bf729326287afa7a5a40fa6ef64a74/core/src/main/resources/create.sql#L1-L25

>Yes but if I put com.mariadb.jdbc.Driver in the parameters for database i get a error

What kind of error... Always post that.

**Comment by LeChevalierDOr** [comment]
```     
     driver: org.mariadb.jdbc.Driver
     host: web01.revhost.fr
     port: 3306
     database: t.....vi..._sk...c
     username: te...vi...r_sk...
     password: 1......00....
     useSSL: false
```

The server tell me :  Could not connect: Access denied for user 'te...vi...r_sk...'@'*.21*.*4.*8' (using password: YES)

Why : *.21*.*4.*8 It's TCP/IP protocol x(

Me : (▽д▽）

**Comment by games647** [comment]
Is the Minecraft server running on the same host? If so, please use an internal IP address. Otherwise you have to configure your MySQL instance to allow external requests. Remember that the username and password are often different to the login data of the web host.
