### ISSUE TITLE
BungeeCord not working SKIN!

### ISSUE THREAD

**Issue by GabrielAugustoTI** [games647/ChangeSkin#36]
20:38:07 [FINE] [ChangeSkin] Making UUID->Name request for Gabriel0Augusto
20:38:09 [SEVERE] [ChangeSkin] null
java.lang.NoSuchFieldException: loginProfile
	at java.lang.Class.getDeclaredField(Unknown Source)
	at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:142)
	at com.github.games647.changeskin.bungee.tasks.SkinUpdater.run(SkinUpdater.java:75)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
20:38:14 [INFO] [Gabriel0Augusto] -> UpstreamBridge has disconnected
20:38:14 [INFO] [Gabriel0Augusto] disconnected with: §f[Proxy] Lost connection to server.
20:38:14 [INFO] [Gabriel0Augusto] <-> DownstreamBridge <-> [hub1] has disconnected
20:38:16 [INFO] [/177.13.227.4:46997] <-> InitialHandler has connected
20:38:16 [SEVERE] [ChangeSkin] null
java.lang.NoSuchFieldException: loginProfile
	at java.lang.Class.getDeclaredField(Unknown Source)
	at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:142)
	at com.github.games647.changeskin.bungee.listener.JoinListener.onPlayerLogin(JoinListener.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:501)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)

Using last version of Bungee, and Spigot 1.10.2!

**Comment by games647** [comment]
Looks like another plugin is overriding the BungeeCord implementation. Could you give me your plugin list please?

**Comment by GabrielAugustoTI** [comment]
ChangeSkin, mcBalancer, ProtocolSupportBungee and SQLibrary-BungeeCord

**Comment by GabrielAugustoTI** [comment]
Please delete your response, i will change the review!

**Comment by games647** [comment]
yeah I was right. I'll investigate how I can work around this.

**Comment by GabrielAugustoTI** [comment]
Plugins folder: https://www.dropbox.com/s/2a64g41rk1qy8h6/Plugins%20Folder.zip?dl=1

**Comment by games647** [comment]
It's conflicting with ProtocolSupport Bungee. I'll write a fix.

**Comment by GabrielAugustoTI** [comment]
I suspect the problem is with the ProtocolSupport, but Spigot, he gives no incompatibility

**Comment by GabrielAugustoTI** [comment]
ProtocolSupportBungee is open source:
https://github.com/ProtocolSupport/ProtocolSupportBungee

**Comment by GabrielAugustoTI** [comment]
Some foresight for fix?

**Comment by GabrielAugustoTI** [comment]
You will upload the fix for Spigotmc?

**Comment by games647** [comment]
yeah, just let me make a coffee. It's too late for me.

**Comment by GabrielAugustoTI** [comment]
You could do something for the community?

Please fix 1.7 join in ProtocolSupportBungee:
https://github.com/ProtocolSupport/ProtocolSupportBungee

The developer is absent :(

Sorry for writing it here, but I have no other place to talk to you

**Comment by games647** [comment]
Proparly because BungeeCord had 1.7.X support before build # 1119

**Comment by GabrielAugustoTI** [comment]
You can fix this?

**Comment by games647** [comment]
No sorry. It's a lot of work.

**Comment by GabrielAugustoTI** [comment]
Bad :(
