### ISSUE TITLE
error on changeskin 2.3

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#42]
Changeskin 2.3, run on Bungeecord with mysql
sometime this error appear in bungeecord console
```
07:46:28 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@31dadd46, id=4397, owner=com.github.games647.changeskin.bungee.ChangeSkinBungee@132e0cc, task=com.github.games647.changeskin.bungee.tasks.NameResolver@175dea4b, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException
	at com.github.games647.changeskin.bungee.tasks.SkinDownloader.run(SkinDownloader.java:41)
	at com.github.games647.changeskin.bungee.tasks.NameResolver.onNameResolve(NameResolver.java:87)
	at com.github.games647.changeskin.bungee.tasks.NameResolver.run(NameResolver.java:71)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by games647** [comment]
Oh,  there is still debug code which created the NPE
