### ISSUE TITLE
Could not load ChangeSkin

### ISSUE THREAD

**Issue by Eufranio** [games647/ChangeSkin#43]
```
[02:07:30] [Server thread/ERROR]: Could not load 'plugins/ChangeSkin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build(Lguava10/com/google/common/cache/CacheLoader;)Lguava10/com/google/common/cache/LoadingCache;
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build(Lguava10/com/google/common/cache/CacheLoader;)Lguava10/com/google/common/cache/LoadingCache;
	at com.github.games647.changeskin.core.ChangeSkinCore.buildCache(ChangeSkinCore.java:48) ~[?:?]
	at com.github.games647.changeskin.bukkit.ChangeSkinBukkit.<init>(ChangeSkinBukkit.java:41) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_101]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_101]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.UNOFFICIAL]
	... 11 more
```

**Comment by games647** [comment]
>org.bukkit.craftbukkit.v1_7_R4

Only compatible with 1.8+

**Comment by Eufranio** [comment]
Oh sorry :/
