### ISSUE TITLE
BungeeCord setup

### ISSUE THREAD

**Issue by TheW4lker** [games647/ChangeSkin#53]
hi
how can setup this plugin in a bungee server?
i do what u said but it still deosnt work

**Comment by games647** [comment]
Please describe it more.

**Comment by TheW4lker** [comment]
i put your plugin in my lobby server and bungee server 
but when i try to do /setskin <skin> it deosnt work at all and not even a msg 
like nothing happend

**Comment by TheW4lker** [comment]
u can join in my server and see if u want :D

**Comment by games647** [comment]
Could you append your server log?

**Comment by TheW4lker** [comment]
when i do /setskin nothing happen at all even in console
also online-mode is false

**Comment by games647** [comment]
Yes because I need your startup log.

**Comment by TheW4lker** [comment]
[m[2K16:09:58 [WARNING] Error enabling plugin ProtocolLib
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more
[m[2K16:09:59 [WARNING] Forced host server pvp is not defined
[m[2K16:09:59 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:18f57f2:1195 by SpigotMC
[m[2K16:09:59 [WARNING] Exception encountered when loading plugin: ChangeSkin
java.lang.RuntimeException: Failed to load class of driverClassName org.sqlite.JDBC
    at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:323)
    at com.github.games647.changeskin.core.SkinStorage.<init>(SkinStorage.java:36)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:89)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:318)
    ... 6 more
[m[2K16:09:59 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:18f57f2:1195 by SpigotMC
[m[2K16:09:59 [INFO]

**Comment by TheW4lker** [comment]
bungee log

**Comment by games647** [comment]
>Failed to load class of driverClassName org.sqlite.JDBC 

You didn't followed the setup guide correctly. See 3. 

>For example BungeeCord doesn't support SQLite by default

**Comment by TheW4lker** [comment]
so what should i do now? :D

**Comment by games647** [comment]
Configure MySQL

**Comment by TheW4lker** [comment]
how?

**Comment by games647** [comment]
Remove the SQLite configuration and enable MySQL in your config and setup all configuration values like username password....

**Comment by TheW4lker** [comment]
Thanks
