### ISSUE TITLE
BungeeCoord dont update skin

### ISSUE THREAD

**Issue by FabioZumbi12** [games647/ChangeSkin#54]
Hi,

I opening here to you have more control over error.

As i posted on your plugin page, the error log on bungee console (not spigot console)

```
02:56:11 [GRAVE] [ChangeSkin] Tried converting player name to uuid from third-party api
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.Gson.fromJson(Gson.java:822)
    at com.google.gson.Gson.fromJson(Gson.java:775)
    at com.google.gson.Gson.fromJson(Gson.java:724)
    at com.google.gson.Gson.fromJson(Gson.java:696)
    at com.github.games647.changeskin.core.MojangSkinApi.getUUIDFromAPI(MojangSkinApi.java:109)
    at com.github.games647.changeskin.core.MojangSkinApi.getUUID(MojangSkinApi.java:63)
    at com.github.games647.changeskin.bungee.tasks.NameResolver.run(NameResolver.java:47)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    ... 10 more
```

Running ChangeSkin alone works fine, but i need to use with bungee :/

**Comment by games647** [comment]
https://github.com/MCAPI-CA/Issues/issues/33

**Comment by games647** [comment]
It's still not working perfectly sorry, but there no good API which can do the same with a good performance and caching system.

**Comment by FabioZumbi12** [comment]
Hum.. i heard SkinRestorer is working fine. Maybe if you see what api SR is using...?

**Comment by games647** [comment]
They use that API too. Now the response is: 
```json
{
    "error": "Proxy overloaded, system cooling down.",
    "status": 429
}
```

**Comment by FabioZumbi12** [comment]
I will try the other ultil this is not solved.

Now with this error, i get  "this is not the username of a paid account" when i try /skin FabioZumbi12 but if i change my skin on mojang and use /skinupdate, the skin updates!

**Comment by games647** [comment]
>Now with this error, when i try /skin FabioZumbi12 i get "this is not the username of a paid account" but if i change my skin on mojang and use /skinupdate, the skin updates!

because that command uses the uuid. The only relevant rate-limit in this case is the name -> uuid query.

**Comment by games647** [comment]
I think it should work now.
