### ISSUE TITLE
Json problem :/

### ISSUE THREAD

**Issue by belfedia** [games647/ChangeSkin#57]
Travertine (waterfall) last version  // paperspigot last version
 
Tried converting player name to uuid from third-party api
/set skin say "queue name to uuid resolve" and "uuid not found" 
bungee console say :
"com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.Gson.fromJson(Gson.java:822)
    at com.google.gson.Gson.fromJson(Gson.java:775)
    at com.google.gson.Gson.fromJson(Gson.java:724)
    at com.google.gson.Gson.fromJson(Gson.java:696)
    at com.github.games647.changeskin.core.MojangSkinApi.getUUIDFromAPI(MojangSkinApi.java:101)
    at com.github.games647.changeskin.core.MojangSkinApi.getUUID(MojangSkinApi.java:59)
    at com.github.games647.changeskin.bungee.tasks.NameResolver.run(NameResolver.java:47)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:70)
    at com.google.gson.Gson.fromJson(Gson.java:810)
    ... 10 more"

And of course, no skin :/

**Comment by games647** [comment]
The website author removed it's support. Related to #55
