### ISSUE TITLE
Skins reset on each player login

### ISSUE THREAD

**Issue by FabioZumbi12** [games647/ChangeSkin#68]
Players with non premium accounts are having your skins reset every login. 
This is the message from BungeeCoord:
```
16:26:41 [SEVERE] [ChangeSkin] Tried converting player name to uuid
com.github.games647.changeskin.core.NotPremiumException: Danielpro12345
    at com.github.games647.changeskin.core.MojangSkinApi.getUUID(MojangSkinApi.java:65)
    at com.github.games647.changeskin.bungee.tasks.NameResolver.run(NameResolver.java:47)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

And this too:

```
16:28:05 [SEVERE] [ChangeSkin] Tried downloading skin data from Mojang
java.io.IOException: Server returned HTTP response code: 429 for URL: https://se
ssionserver.mojang.com/session/minecraft/profile/17bb7e1f4f804fbe93e62cfa2c68cf4b?unsigned=false
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at com.github.games647.changeskin.core.MojangSkinApi.downloadSkin(MojangSkinApi.java:103)
    at com.github.games647.changeskin.bungee.tasks.SkinInvalidater.run(SkinInvalidater.java:36)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
(all from bungeecoord)

And when player use the /skin command from server, this is the message (from server console):

```
[16:30:00 INFO]: [ChangeSkin] Instant update for marcosellwanger
[16:30:00 WARN]: marcosellwanger moved too quickly! -3913.1222959751967,164.0,6870.571291318957
```

Seems to be like the player is on boat or flying with elytro, and this causes that other problem with the world is invisible.

Using your latest jenkings build and running on 1.11.2.
That other error whas fixed after update to latest protocollib.

**Comment by games647** [comment]
I need your plugins list and if you use heads.

**Comment by FabioZumbi12** [comment]
This is my server plug-ins:

```
[17:21:37 INFO]: Plugins (76): Vehicles, neoPaintingSwitch, PerWorldPlugins, Her
obrine, BetterChairs, LoreTag, ChatReaction, MaxBans, Televator, TrophyHeads, Lo
ckMe, Tablist, BetterAlias, AsyncWorldEditInjector, CoreProtect, JM, WorldEdit, 
OpenInv, WorldBorder, Votifier, SilkSpawners, ProtocolLib, ClientPermissions, Mu
ltiverse-Core, DeathMessagesPrime, AutoSaveWorld, SignEdit, AsyncWorldEdit, Reac
t, MinEmojis, ShopTeleport, PermissionsEx, mcMMO, Multiverse-Portals, GAListener
, Vault, DailyRewards, ChestShop, LotteryZero, RankUpper, PerWorldInventory, Mob
Stacker, MysqlEconomyBank, CraftBay, ParticleHats, afkTerminator, InfernalMobs, 
ExpBank, TheEndRegen, Orebfuscator4, ButtonWarp, Essentials, MarriageMaster, Cha
ngeSkin, Multiverse-EssentialsSupport, SimpleClans, Citizens, UltimateChat, Shop
keepers, DiscordSRV, TreeAssist, ColoredTablist, PixelVip, EssentialsGeoIP, Butt
onWarpRandom, EssentialsSpawn, PvPManager, CompatNoCheatPlus, ScoreboardStats, NoCheatPlus, LeaderHeads, LetItRain, MyPet, MagicCarpet, RedProtect, PvPDiffTimer

```

And this is my BungeeCoord plugins (i using with bungeecoord):

http://prntscr.com/fgplqb

**Comment by AodX** [comment]
@games647 i have the same problem

when cracked players join the server, they won't get their skin that they had :(
It was working well on Spigot

but since i have Bungeecord its not working 
So its maybe a MySQL Thing ? or a Coding for bungeecord ?

can you help us :( ?

**Comment by games647** [comment]
@AodX See #86

**Comment by AodX** [comment]
@games647 but he didn't fix anything ...

**Comment by games647** [comment]
Just see my last comment

**Comment by FabioZumbi12** [comment]
I changed to SkinRestore due too long time without news about this issue, then i cant say if is working or not. 

If you want, you can close this issue based if is working for @AodX .
