### ISSUE TITLE
Problem on bungeecord

### ISSUE THREAD

**Issue by belfedia** [games647/ChangeSkin#70]
11:38:56 [GRAVE] juin 09, 2017 11:38:56 AM net.md_5.bungee.event.EventBus post
AVERTISSEMENT: Error dispatching event PostLoginEvent(player=The) to listener com.github.games647.changeskin.bungee.listener.JoinListener@5abf9a76
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:168)
    at com.github.games647.changeskin.bungee.listener.JoinListener.onPlayerLogin(JoinListener.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:376)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:515)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)

I have this message on bungeecord each time i use /setskin command :/ and skin don't appear.
I use latest waterfall, Paperspigot last 1.11.2 and viaversion1.1.1.

**Comment by games647** [comment]
Update ChangeSkin from here: https://ci.xephi.fr/job/ChangeSkin/

**Comment by belfedia** [comment]
Problem  is solved !
Thanks

**Comment by yashiro1986** [comment]
Login to https://ci.xephi.fr/job/ChangeSkin/ and I get several files .jar which of all I choose or how it is updated

**Comment by games647** [comment]
The one with the ChangeSkin.jar name.
