### ISSUE TITLE
Problem with bungeecord and 1.12

### ISSUE THREAD

**Issue by EverMineServer** [games647/ChangeSkin#72]
I use the last build of bungeecord and your plugin don't work, please make it compatible with last version of bungeecord. :'(

**Comment by EverMineServer** [comment]
07:04:49 [BUONO] [ChangeSkin] Making UUID->Name request for SMILEYpes
07:04:51 [GRAVE] giu 15, 2017 7:04:51 AM net.md_5.bungee.event.EventBus post
AVVERTENZA: Error dispatching event PostLoginEvent(player=SMILEYpes) to listener com.github.games647.changeskin.bungee.listener.JoinListener@3a393455
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
	at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:168)
	at com.github.games647.changeskin.bungee.listener.JoinListener.onPlayerLogin(JoinListener.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:376)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:515)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by games647** [comment]
Duplicate #70
