### ISSUE TITLE
error

### ISSUE THREAD

**Issue by friishon** [games647/ChangeSkin#73]
i have this error on bungee
18:49:57 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@3daf7722, id=1313, owner=com.github.games647.changeskin.bungee.ChangeSkinBungee@3078cac, task=com.github.games647.changeskin.bungee.listener.ServerSwitchListener$1@2c0e75b4, delay=0, period=0, running=true) encountered an exception
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:168)
    at com.github.games647.changeskin.bungee.listener.ServerSwitchListener.onLazyLoad(ServerSwitchListener.java:54)
    at com.github.games647.changeskin.bungee.listener.ServerSwitchListener.access$000(ServerSwitchListener.java:16)
    at com.github.games647.changeskin.bungee.listener.ServerSwitchListener$1.run(ServerSwitchListener.java:33)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
i use 1.12 server and latest changeskin

**Comment by games647** [comment]
Duplicate #72
