### ISSUE TITLE
ChangeSkin + BungeeCord + Spigot 1.8.8

### ISSUE THREAD

**Issue by Spikey101** [games647/ChangeSkin#75]
Hello,
I am using ChangeSkin with BungeeCord and Spigot 1.8.8, I put the jar file in my BungeeCord directory, and each of my Spigots directory. When I start BungeeCord I get the error below. I have downloaded it from  https://ci.xephi.fr/job/ChangeSkin/
``
15:55:05 [WARNING] Exception encountered when loading plugin: ChangeSkin
java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203)
    at java.nio.file.Files.copy(Files.java:2984)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.saveDefaultResource(ChangeSkinBungee.java:124)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:63)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
``

List of plugins in /BungeeCord/plugins

YAMLER-Bungee-2.4.0-SHANPSHOP
VPNGuardBungee
Movemenow-1.2-17.jar
LuckPerms-Bungee-3.2.25
FastLogin
CommandControl
BungeeChat-2.0.3.2_643
BungeeAuthMeBridge
BungeeAdminTools-1.4.3-basics

Let me know if a list of plugins is needed on my Spigot server as well, but the error only appears in my BungeeCord console.

**Comment by Spikey101** [comment]
I also get this when starting my Spigot server, I also redownloaded from Xephi and am using ChangeSkins-Bukkit.jar... .

`[16:00:22] [Server thread/ERROR]: Could not load 'plugins/ChangeSkinBukkit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/github/games647/changeskin/core/ChangeSkinCore
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8.8.jar:git-Spigot-21fe7$
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8.8.jar:git-Spigot-21fe$
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8.8.jar:git-Spigot-21fe$
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-21fe707$
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-21fe707-$
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e$
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: com/github/games647/changeskin/core/ChangeSkinCore
        at com.github.games647.changeskin.bukkit.ChangeSkinBukkit.<init>(ChangeSkinBukkit.java:42) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_13$
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_131]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8.8.jar:git-Spigot-21fe707-$
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8.8.jar:git-Spigot-21fe7$
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.github.games647.changeskin.core.ChangeSkinCore
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe$
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe7$
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
        at com.github.games647.changeskin.bukkit.ChangeSkinBukkit.<init>(ChangeSkinBukkit.java:42) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_131]
`

**Comment by games647** [comment]
You need universal.

**Comment by Spikey101** [comment]
Where do I get "Universal" ? Is that an independant plugin? I don't get it, I don't see any jar file named "Universal" on the Xephi page. thanks

**Comment by Spikey101** [comment]
This is universal: https://www.spigotmc.org/resources/changeskin.21469/ ?

I had that at first, but it gave me an error, and then you posted to get it from Xephi, I got it from Xephi, Now I'm supposed to go back to the old one that give me the error?

**Comment by Spikey101** [comment]
> Update ChangeSkin from here: https://ci.xephi.fr/job/ChangeSkin/

**Comment by games647** [comment]
No it's ChangeSkin.jar. I forgot that I rename it to the normal plugin name.

**Comment by Spikey101** [comment]
Thanks, I changed it and now the skins are working perfectly. A little off-topic: I was wondering is there anyway I can get the skull of a cracked player with /skull? Where it gets the skull from the ChangeSkin database rather than Mojang? Because right now let's say a cracked player does /setskin Sloth and then does /skull crackedplayername it gives a default head, rather than Sloth.. Thanks though

**Comment by games647** [comment]
There is no official API provided by Bukkit, so it would require to interact with the nbt directly. So it's possible but not that easy. You could even do it with the vanilla commands if you know how to base64 decode the data from mojang requests.
