### ISSUE TITLE
Tried converting player name to uuid

### ISSUE THREAD

**Issue by EverMineServer** [games647/ChangeSkin#76]
15:12:50 [GRAVE] [ChangeSkin] Tried converting player name to uuid
com.github.games647.changeskin.core.NotPremiumException: culio04
    at com.github.games647.changeskin.core.MojangSkinApi.getUUID(MojangSkinApi.java:65)
    at com.github.games647.changeskin.bungee.listener.AbstractSkinListener.refetch(AbstractSkinListener.java:32)
    at com.github.games647.changeskin.bungee.listener.LoginListener.lambda$refetchSkin$0(LoginListener.java:48)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by games647** [comment]
Just ignore it or download a dev-build from https://ci.xephi.fr/job/ChangeSkin/

**Comment by EverMineServer** [comment]
For my bungeecord i can use ChangeSkin.jar or ChangeSkinBungee.jar?

**Comment by games647** [comment]
The normal file for both of your servers.
