### ISSUE TITLE
skin upload error

### ISSUE THREAD

**Issue by VailRyen** [games647/ChangeSkin#77]
hello i report /skinupload error
its upload working, but following errors
Test URL : http://i.imgur.com/4lV1m26.png

> `[20:07:22 WARN]: [ChangeSkin] Plugin ChangeSkin v2.3.2 generated an exception while executing task 57241
java.lang.NullPointerException
        at java.net.URLEncoder.encode(Unknown Source) ~[?:1.8.0_131]
        at com.github.games647.changeskin.core.MojangAuthApi.changeSkin(MojangAuthApi.java:90) ~[?:?]
        at com.github.games647.changeskin.bukkit.tasks.SkinUploader.run(SkinUploader.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1104]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1104]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

**Comment by games647** [comment]
How did you invoke the command exactly?

**Comment by VailRyen** [comment]
sorry for very late reply

i use only /skinupload url

and, strange...  after that I tried again and it works perfectly.
