### ISSUE TITLE
Plugin does not create the Folder

### ISSUE THREAD

**Issue by Apolo-Yt** [games647/ChangeSkin#78]
I'm having problems configuring the plugin because when I put it in the plugins folder it does not create the configuration folder

**Comment by games647** [comment]
What does your server log say?

**Comment by Apolo-Yt** [comment]
[17:58:30] [Server thread/INFO]: Starting minecraft server version 1.8
[17:58:31] [Server thread/INFO]: Loading properties
[17:58:31] [Server thread/INFO]: Default game type: SURVIVAL
[17:58:31] [Server thread/INFO]: Generating keypair
[17:58:31] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:25567
[17:58:31] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[17:58:31] [Server thread/WARN]: Plugin `Administration_Panel v1.1.0' uses the space-character (0x20) in its name `Administration Panel' - this is discouraged
[17:58:31] [Server thread/ERROR]: Could not load 'plugins\ChangeSkin.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:58:31] [Server thread/ERROR]: Could not load 'plugins\iGates.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PluginsBaker
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:58:31] [Server thread/ERROR]: Could not load 'plugins\PAC.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: ProtocolLib
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-33d5de3]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-33d5de3]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-33d5de3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[17:58:32] [Server thread/INFO]: [Announcement] Loading Announcement v1.0.3
[17:58:32] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.0;3342-78f975b9
[17:58:32] [Server thread/INFO]: [ColoredSigns] Loading ColoredSigns v2.0
[17:58:32] [Server thread/INFO]: [Essentials] Loading Essentials vTeamCity
[17:58:32] [Server thread/INFO]: [SeTheMOTD] Loading SeTheMOTD v1.0
[17:58:32] [Server thread/INFO]: [ClearLag] Loading ClearLag v2.9.7
[17:58:32] [Server thread/INFO]: [PerWorldPlugins] Loading PerWorldPlugins v1.3.0
[17:58:32] [Server thread/INFO]: [PerWorldPlugins] Registering event interceptor...
[17:58:32] [Server thread/INFO]: [Administration_Panel] Loading Administration_Panel v1.1.0
[17:58:32] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5-b699
[17:58:32] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.0.0-beta-05.1569-
[17:58:32] [Server thread/INFO]: [InfoBoardReborn] Loading InfoBoardReborn v1.7.0
[17:58:32] [Server thread/INFO]: [BungeePortals] Loading BungeePortals v1.2
[17:58:32] [Server thread/INFO]: [ItemStay] Loading ItemStay v1.5.6
[17:58:32] [Server thread/INFO]: [TGReport] Loading TGReport v1.1
[17:58:32] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect vTeamCity
[17:58:32] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat vTeamCity
[17:58:32] [Server thread/INFO]: [iConomy] Loading iConomy v7.0.6
[17:58:32] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[17:58:32] [Server thread/INFO]: [SignEditor] Loading SignEditor v1.07
[17:58:32] [Server thread/INFO]: [CustomJoinItems] Loading CustomJoinItems v1.5.2
[17:58:32] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[17:58:32] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn vTeamCity
[17:58:32] [Server thread/INFO]: [MassiveCore] Loading MassiveCore v2.8.5
[17:58:32] [Server thread/INFO]: TimeUnit.MILLIS_PER_MINUTE: 60000
[17:58:32] [Server thread/INFO]: [ClickWarp] Loading ClickWarp v1.3.5
[17:58:32] [Server thread/INFO]: [AntiXRay] Loading AntiXRay v1.8.5
[17:58:32] [Server thread/INFO]: [ChestShop] Loading ChestShop v3.8.12
[17:58:32] [Server thread/INFO]: [HolographicDisplays] Loading HolographicDisplays v2.2.6
[17:58:32] [Server thread/INFO]: [VipZero] Loading VipZero v1.2.4
[17:58:32] [Server thread/INFO]: [ServerSigns] Loading ServerSigns v4.2.1-DEV
[17:58:32] [Server thread/INFO]: [MinigamesLib] Loading MinigamesLib v1.13.1
[17:58:32] [Server thread/INFO]: [MGSkyWars] Loading MGSkyWars v1.5.2
[17:58:32] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[17:58:32] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[17:58:32] [Server thread/WARN]: iConomy - If you are using Flatfile storage be aware that versions 6, 7 and 8 have a CRITICAL bug which can wipe ALL iconomy data.
[17:58:32] [Server thread/WARN]: if you're using Votifier, or any other plugin which handles economy data in a threaded manner your server is at risk!
[17:58:32] [Server thread/WARN]: it is highly suggested to use SQL with iCo6 or to use an alternative economy plugin!
[17:58:32] [Server thread/INFO]: [Vault] [Economy] iConomy 6 found: Waiting
[17:58:32] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[17:58:32] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[17:58:32] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[17:58:32] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[17:58:32] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v2.8.5
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] === ENABLE START ===
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §eLoading Cachefile datas...
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §eLoading Onlineplayer datas...
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §eLoading Registry datas...
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §eSaving Cachefile...
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §eSetup of IdUtil took §d34§ems.
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] §aActivated §eintegration with §dVault
[17:58:32] [Server thread/INFO]: [MassiveCore 2.8.5] === ENABLE §aCOMPLETE §e(Took §d342ms§e) ===
[17:58:33] [Server thread/INFO]: Preparing level "world"
[17:58:33] [Server thread/INFO]: Preparing start region for level 0 (Seed: -4673027410516377731)
[17:58:33] [Server thread/INFO]: Preparing start region for level 1 (Seed: -4673027410516377731)
[17:58:34] [Server thread/INFO]: Preparing start region for level 2 (Seed: -4673027410516377731)
[17:58:34] [Server thread/INFO]: [Announcement] Enabling Announcement v1.0.3
[17:58:34] [Server thread/INFO]: [Announcement] Config Loaded
[17:58:34] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.0;3342-78f975b9
[17:58:35] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[17:58:35] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
[17:58:35] [Server thread/INFO]: [ColoredSigns] Enabling ColoredSigns v2.0
[17:58:35] [Server thread/INFO]: [ColoredSigns] ColoredSigns enabling.
[17:58:35] [Server thread/WARN]: [ColoredSigns] PermissionsEx support is enabled.
[17:58:35] [Server thread/INFO]: [ColoredSigns] Starting services.. loading file and library's.
[17:58:35] [Server thread/INFO]: [Essentials] Enabling Essentials vTeamCity
[17:58:35] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[17:58:35] [Server thread/INFO]: git-Bukkit-33d5de3 (MC: 1.8)
[17:58:35] [Server thread/INFO]: 1.8-R0.1-SNAPSHOT
[17:58:35] [Server thread/INFO]: Using locale en_BR
[17:58:35] [Server thread/INFO]: Using locale en_BR
[17:58:35] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[17:58:35] [Server thread/INFO]: Essentials: Using config file enhanced permissions.
[17:58:35] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
[17:58:35] [Server thread/INFO]: [Essentials] Payment method found (Vault - Economy: iConomy  version: 1.5.6-b49)
[17:58:35] [Server thread/INFO]: [SeTheMOTD] Enabling SeTheMOTD v1.0
[17:58:35] [Server thread/INFO]: [SeTheMOTD] Plugin created by: XOntorX
[17:58:35] [Server thread/INFO]: [ClearLag] Enabling ClearLag v2.9.7
[17:58:35] [Server thread/INFO]: [ClearLag] Loading modules...
[17:58:35] [Server thread/INFO]: [ClearLag] Modules enabed, loading config values
[17:58:35] [Server thread/INFO]: [ClearLag] Modules have been loaded!
[17:58:35] [Server thread/INFO]: [ClearLag] Clearlag is now enabled!
[17:58:35] [Server thread/INFO]: [PerWorldPlugins] Enabling PerWorldPlugins v1.3.0
[17:58:35] [Server thread/INFO]: [PerWorldPlugins] Enabled, attempting to inject CommandHandler...
[17:58:35] [Thread-16/INFO]: [ClearLag] Checking for updates compatible with your bukkit version [1.8]...
[17:58:35] [Server thread/INFO]: [Administration_Panel] Enabling Administration_Panel v1.1.0
[17:58:35] [Server thread/INFO]: [AdministrationPanel]: Administration_Panel v1.1.0 has been enabled!
[17:58:35] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5-b699
[17:58:35] [Server thread/INFO]: Preparing start region for level 3 (Seed: 6187964276842831451)
[17:58:36] [Thread-16/INFO]: [ClearLag] No updates found!
[17:58:37] [Server thread/INFO]: Preparing spawn area for lobby, 85%
[17:58:37] [Server thread/INFO]: Preparing start region for level 4 (Seed: -5265399852203765885)
[17:58:37] [Server thread/INFO]: Preparing start region for level 5 (Seed: -8844959533198030485)
[17:58:37] [Server thread/INFO]: [Multiverse-Core] 6 - World(s) loaded.
[17:58:37] [Server thread/INFO]: [Multiverse-Core] Version 2.5-b699 (API v19) Enabled - By Rigby, fernferret, lithium3141 and main--
[17:58:37] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.0.0-beta-05.1569-
[17:58:37] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[17:58:37] [Server thread/INFO]: [WorldGuard] (lobby) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (lobby) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (lobby) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (lobby) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'lobby'
[17:58:37] [Server thread/INFO]: [WorldGuard] (arenagelo) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (arenagelo) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (arenagelo) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (arenagelo) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'arenagelo'
[17:58:37] [Server thread/INFO]: [WorldGuard] (skywars) TNT ignition is PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (skywars) Lighters are PERMITTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] (skywars) Lava fire is blocked.
[17:58:37] [Server thread/INFO]: [WorldGuard] (skywars) Fire spread is UNRESTRICTED.
[17:58:37] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'skywars'
[17:58:37] [Server thread/INFO]: [WorldGuard] Loading region data...
[17:58:38] [Server thread/INFO]: [InfoBoardReborn] Enabling InfoBoardReborn v1.7.0
[17:58:38] [Server thread/INFO]: Metrics was started!
[17:58:38] [Server thread/INFO]: [BungeePortals] Enabling BungeePortals v1.2
[17:58:38] [Server thread/INFO]: [BungeePortals] Metrics initiated!
[17:58:38] [Server thread/INFO]: [BungeePortals] Commands registered!
[17:58:38] [Server thread/INFO]: [BungeePortals] Events registered!
[17:58:38] [Server thread/INFO]: [BungeePortals] Plugin channel registered!
[17:58:38] [Server thread/INFO]: [BungeePortals] Configuration file config.yml loaded!
[17:58:38] [Server thread/INFO]: [BungeePortals] Configuration file portals.yml loaded!
[17:58:38] [Server thread/INFO]: [BungeePortals] Portal data loaded! (0ms)
[17:58:38] [Server thread/INFO]: [BungeePortals] Save task started!
[17:58:38] [Server thread/INFO]: [BungeePortals] Version 1.2 has been enabled. (15ms)
[17:58:38] [Server thread/INFO]: [ItemStay] Enabling ItemStay v1.5.6
[17:58:38] [Server thread/INFO]: [TGReport] Enabling TGReport v1.1
[17:58:38] [Server thread/INFO]: Ativando o Plugin...
[17:58:38] [Server thread/INFO]: Plugin Ativo. Author: Trow
[17:58:38] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect vTeamCity
[17:58:38] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vTeamCity
[17:58:38] [Server thread/INFO]: [iConomy] Enabling iConomy v7.0.6
[17:58:38] [Server thread/INFO]: [iConomy - April Fools] Enabled (19 ms)
[17:58:38] [Server thread/INFO]: [iConomy] Hello, I'm Nijikokun. Yes, this is an April Fools joke, but '/money top' was fixed! Enjoy :) - Rare Version!
[17:58:38] [Server thread/INFO]: [Vault][Economy] iConomy 7 hooked.
[17:58:38] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[17:58:38] [Thread-18/INFO]: [iConomy - April Fools] Purged accounts with default balance.
[17:58:38] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[17:58:38] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[17:58:38] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[17:58:38] [Server thread/INFO]: [Vault][Permission] PermissionsEx hooked.
[17:58:38] [Server thread/INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[17:58:38] [Server thread/INFO]: Essentials: Using PermissionsEx based permissions.
[17:58:38] [Server thread/INFO]: [SignEditor] Enabling SignEditor v1.07
[17:58:38] [Server thread/INFO]: [CustomJoinItems] Enabling CustomJoinItems v1.5.2
[17:58:38] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vTeamCity
[17:58:38] [Server thread/INFO]: [ClickWarp] Enabling ClickWarp v1.3.5
[17:58:38] [Server thread/INFO]: [ClickWarp] Metrics started!
[17:58:38] [Server thread/INFO]: [ClickWarp] Plugin v1.3.5 by comniemeer enabled.
[17:58:38] [Server thread/INFO]: [AntiXRay] Enabling AntiXRay v1.8.5
[17:58:39] [Server thread/ERROR]: [AntiXRay] Plugin AntiXRay v1.8.5 has failed to register events for class me.ryanhamshire.AntiXRay.ExplosionsListener because org/bukkit/event/block/BlockExplodeEvent does not exist.
[17:58:39] [Server thread/INFO]: [ChestShop] Enabling ChestShop v3.8.12
[17:58:39] [Server thread/ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[17:58:39] [Server thread/INFO]: creating table 'items'
[17:58:39] [Server thread/INFO]: executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT , `code` VARCHAR NOT NULL ,  UNIQUE (`code`)) 
[17:58:39] [Server thread/ERROR]: WARNING: you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite
[17:58:39] [Server thread/INFO]: creating table 'accounts'
[17:58:39] [Server thread/INFO]: creating index 'accounts_shortName_idx' for table 'accounts
[17:58:39] [Server thread/INFO]: executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS `accounts` (`lastSeenName` VARCHAR NOT NULL , `name` VARCHAR NOT NULL , `shortName` VARCHAR NOT NULL , `uuid` VARCHAR NOT NULL , PRIMARY KEY (`name`) ) 
[17:58:39] [Server thread/INFO]: executed create table statement changed 0 rows: CREATE INDEX IF NOT EXISTS `accounts_shortName_idx` ON `accounts` ( `shortName` )
[17:58:39] [Server thread/INFO]: [ChestShop] Vault loaded! Found an economy plugin!
[17:58:39] [Server thread/INFO]: [HolographicDisplays] Enabling HolographicDisplays v2.2.6
[17:58:39] [Server thread/INFO]: [VipZero] Enabling VipZero v1.2.4
[17:58:39] [Server thread/INFO]: [VipZero] Enabling VipZero (V1.2.4) - Author: SubZero0 & nathampa0909
[17:58:39] [Server thread/INFO]: [VipZero] Checking for updates...
[17:58:40] [Server thread/INFO]: [VipZero] No updates found.
[17:58:40] [Server thread/INFO]: [VipZero] Checking for old config file...
[17:58:40] [Server thread/INFO]: [VipZero] No updates found.
[17:58:40] [Server thread/INFO]: [VipZero] Checking for config file update...
[17:58:40] [Server thread/INFO]: [VipZero] No updates found.
[17:58:40] [Server thread/INFO]: [VipZero] Checking for language file update...
[17:58:40] [Server thread/INFO]: [VipZero] No updates found.
[17:58:40] [Server thread/INFO]: [VipZero] Using flatfile system.
[17:58:40] [Server thread/INFO]: [VipZero] Use only Vault for permissions: ENABLED!
[17:58:40] [Server thread/INFO]: [VipZero] Hooked to Vault (Permission).
[17:58:40] [Server thread/INFO]: [VipZero] Hooked to Vault (Economy).
[17:58:40] [Server thread/INFO]: [ServerSigns] Enabling ServerSigns v4.2.1-DEV
[17:58:40] [Server thread/INFO]: [ServerSigns] Successfully hooked into dependencies
[17:58:40] [Server thread/INFO]: [ServerSigns] Version 4.2.1-DEV is now enabled.
[17:58:40] [Server thread/INFO]: [MinigamesLib] Enabling MinigamesLib v1.13.1
[17:58:40] [Server thread/INFO]: Loaded MinigamesAPI. We're on v1_8_R1.
[17:58:40] [Server thread/INFO]: [MGSkyWars] Enabling MGSkyWars v1.5.2
[17:58:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:58:40] [Server thread/INFO]: Done (8.036s)! For help, type "help" or "?"
[17:58:41] [pool-3-thread-2/INFO]: [Vault] Checking for Updates ... 
[17:58:41] [pool-3-thread-2/INFO]: [Vault] No new version available
[17:58:41] [pool-3-thread-4/INFO]: [Metrics] Unexpected end of file from server
[17:58:43] [Server thread/INFO]: false
[17:58:43] [Server thread/INFO]: false
[17:58:43] [Server thread/INFO]: Found 2 arenas.

**Comment by games647** [comment]
How about that: Cannot check bungeecord support. You use a non-spigot build

Please use Spigot. It's from the same developers.
