### ISSUE TITLE
Bungeecord console error when i do /skinupdate or /changeskin or /setskin

### ISSUE THREAD

**Issue by LoryWasHere** [games647/ChangeSkin#80]
When i do any command of ChangeSkin, it says this in console (bungee):

23:10:12 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4b741d6d, id=5, owner=com.github.games647.changeskin.bungee.ChangeSkinBungee@1ed6388a, task=com.github.games647.changeskin.bungee.tasks.SkinUpdater@3722278a, delay=0, period=0, running=true) encountered an exception
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.applySkin(ChangeSkinBungee.java:162)
    at com.github.games647.changeskin.bungee.tasks.SkinUpdater.run(SkinUpdater.java:71)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Can i have some help?

**Comment by games647** [comment]
Please update it to a dev-build. It's already fixed.
