### ISSUE TITLE
org.bukkit.Bukkit.spigot()Lorg/bukkit/Server$Spigot

### ISSUE THREAD

**Issue by KryanThePacifist** [games647/ChangeSkin#9]
Hey.
So i tried this in every server build i could think of, but neither Spiggot or Bukkit Work with this plugin.
Here's my console output in Server Load:
[05:18:48 ERROR]: Could not load 'plugins/ChangeSkin.jar' in folder 'plugins' org.bukkit.plugin.UnknownDependencyException: ProtocolLib at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:293) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.<init>(CraftServer.java:255) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:182) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
My server is hosted in server.pro as a free server. so its not a dedicated server as far as i can tell.
Thanks :D

**Comment by games647** [comment]
>UnknownDependencyException: ProtocolLib

You have to install the plugin ProtocolLib.

**Comment by KryanThePacifist** [comment]
Ok so i did installed the ProtocolLib plugin but it then bounced me a diferent error.
[21:14:43 ERROR]: Error occurred while enabling ChangeSkin v1.0 (Is it up to date?) java.lang.NoSuchMethodError: org.bukkit.Bukkit.spigot()Lorg/bukkit/Server$Spigot; at com.github.games647.changeskin.bukkit.ChangeSkinBukkit.onEnable(ChangeSkinBukkit.java:28) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:346) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:318) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:403) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:368) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:323) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:241) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Is it due to being Bukkit or something else i'm missing here?
Thanks for your time :D

**Comment by games647** [comment]
>NoSuchMethodError: org.bukkit.Bukkit.spigot()Lorg/bukkit/Server$Spigot

The plugin expects a Spigot server, but you are running Craftbukkit. Normally it should work also with Craftbukkit, but the recommended server software is Spigot (better performance).

I'm going to fix it.

**Comment by games647** [comment]
Update is uploaded

**Comment by KryanThePacifist** [comment]
Thanks. Got it working. Just a quick question, Is there a list of Skins or a site where this plugin dowloadts it from? wanna know so i can see the list of skins with my friends.
Thanks for your time :D

**Comment by games647** [comment]
It downloads it directly from Mojang. I don't know a website which could do that, sorry.

**Comment by KryanThePacifist** [comment]
No problem. Mojang it is. Thanks you so much for your time, this plugin made my server Players really happy.
Keep up the Good work :D
