### ISSUE TITLE
Failed to query preferences

### ISSUE THREAD

**Issue by Sakanas** [games647/ChangeSkin#93]
```
[00:19:59] [User Authenticator #594/ERROR]: [ChangeSkin] Failed to query preferences
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.DB.prepare(DB.java:227) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at com.zaxxer.hikari.proxy.ConnectionProxy.prepareStatement(ConnectionProxy.java:265) ~[VotingPlugin%20(7).jar:?]
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.prepareStatement(HikariConnectionProxy.java) ~[VotingPlugin%20(7).jar:?]
	at com.github.games647.changeskin.core.SkinStorage.getPreferences(SkinStorage.java:99) [ChangeSkin%20(4).jar:?]
	at com.github.games647.changeskin.bukkit.listener.AsyncLoginListener.onPreLogin(AsyncLoginListener.java:38) [ChangeSkin%20(4).jar:?]
	at sun.reflect.GeneratedMethodAccessor443.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:271) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.LoginListener$2.run(LoginListener.java:187) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
```

**Comment by games647** [comment]
Which plugin version do you run? Are multiple servers accessing the same database file?

**Comment by Sakanas** [comment]
[ChangeSkin] Enabling ChangeSkin v3.0
Build #33
only 1 server

**Comment by games647** [comment]
I thought Hikari would limit the connection pool automatically. It looks like I was wrong.
