### ISSUE TITLE
bungeeCord console erorr!

### ISSUE THREAD

**Issue by kickme2** [games647/ChangeSkin#97]
Hello, there is erorr of my console,
i have bungeecord server, with 2GB of ram
Here is the console log, which happend when I installed the plugin: ChangeSkin

[m[2K18:27:05 [WARNING] Exception encountered when loading plugin: ChangeSkin
java.lang.RuntimeException: Failed to load class of driverClassName [org.sqlite.JDBC] in either of HikariConfig class loader or Thread context classloader
    at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:332)
    at com.github.games647.changeskin.core.SkinStorage.<init>(SkinStorage.java:37)
    at com.github.games647.changeskin.bungee.ChangeSkinBungee.onEnable(ChangeSkinBungee.java:96)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by games647** [comment]
Please follow: https://github.com/games647/ChangeSkin#how-to-install-on-bungeecord
